### ISSUE TITLE
missing url

### ISSUE THREAD

**Issue by pezongod** [Hanndel/RaidHelper#1]
Hi Hanndel!

Great repos, but when I try starting it up it fails because there is 2 missing url:s. One for IpResponse and one for IvResponse. 
Could you provide those?

Thanx!

Pezongod

**Comment by Hanndel** [comment]
Those are Url's to the public key used to decrypt my personal ip, as I was hosting the auth server in my raspberri, sadly i can't provide those.

**Comment by pezongod** [comment]
thank you for your quick response, then I know :)
